"""Find mentions. Regular expressions catch structured identifiers; Apertus finds names and their roles.

Apertus only labels: every mention it returns must occur verbatim in the excerpt, or it is dropped.
The text itself is never generated by the model.
"""

import re
from dataclasses import dataclass

from .llm import LLMError, chat_json, chat_list, salvage_items

TYPES = [
    "private_person",
    "private_company",
    "lawyer",
    "court_official",
    "expert",
    "authority",
    "public_body",
    "residence",
    "place",
    "address",
    "identifier",
    "parcel_number",
    "occupation",
    "birth_date",
]
LANGUAGES = {"de": "German", "fr": "French", "it": "Italian"}

# Property names are chosen so that alphabetical order (which some servers impose on the
# grammar) matches the order the model should think in: copy the mention, then name its role,
# then pick the type.
SCHEMA = {
    "type": "object",
    "properties": {
        "mentions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "mention": {"type": "string"},
                    "role": {"type": "string"},
                    "type": {"type": "string", "enum": TYPES},
                },
                "required": ["mention", "role", "type"],
            },
            "maxItems": 60,  # 60 items of about 40 tokens fit under max_tokens, so a repetition loop stops at the cap
        }
    },
    "required": ["mentions"],
}

SYSTEM = (
    "You annotate Swiss court decisions for anonymisation. You list mentions exactly as they "
    "are written in the text and classify each one by the role it plays in the proceedings. "
    "You never add text that is not in the excerpt."
)

PROMPT = """Decision language: {language}.
{known}
Annotate the excerpt below. List every mention of:
- private_person: a natural person involved privately: party, accused, victim, witness, relative, heir, employee, a doctor, psychologist or therapist who treated a party, an expert hired by a party, or a representative who is not a lawyer
- private_company: a company, shop, restaurant, hotel, farm, private clinic, bank, association, foundation, estate of a deceased person, or any other private organisation, also one named after a person such as "Società Nessi" (the legal form such as AG, SA, Sagl may be left out)
- lawyer: a lawyer representing a party (Rechtsanwalt, Fürsprecher, avocat, Me, avv.)
- court_official: a judge, court clerk (Gerichtsschreiber, greffier, cancelliere), prosecutor or member of an authority
- expert: an expert appointed by a court or authority to give an opinion (Gutachter, expert judiciaire, perito), or a medical service commissioned by an authority to examine a party
- authority: a court, authority, office, public institution such as a public hospital or university, canton or the Confederation
- public_body: a municipality or other public-law corporation that is itself a party
- residence: a place name that says where a private party lives or has its seat, also inside a court name such as "Bezirksgericht X" when X is the party's district
- place: any other place name
- address: a street address, PO box or postcode with town
- identifier: a social security (AHV/AVS) number, IBAN or account number, phone number, e-mail address or vehicle registration plate
- parcel_number: a land register or cadastral parcel number
- occupation: the job of a private person, e.g. "Chef-Automechaniker", "infirmière"
- birth_date: the birth date or birth year of a private person

Rules:
- Copy each mention exactly as written, without titles such as Herr, Frau, Dr., Me, avv., Bundesrichter.
- One name per mention: write "Anna Meier" and "Peter Keller" as two mentions, never "Anna Meier und Peter Keller". Names in enumerations and in parentheses count too.
- Give the role in a few words, e.g. "Beschwerdeführer", "judge", "lawyer of the appellant", "employer of the appellant"; use "" for places and numbers.
- Skip role words without a name (der Beschwerdeführer, la recourante, il ricorrente), legal provisions, case numbers, and dates other than birth dates.
- Text that is already anonymised (A.________, X.________, [...]) is not a mention.
- List each distinct mention once.

Excerpt:
<<<
{text}
>>>"""

TITLES = re.compile(
    r"^(?:(?:Herrn?|Frau|Dr\.|Dres\.|Prof\.|lic\.|iur\.|med\.|phil\.|Rechtsanwalt|Rechtsanwältin|RA|"
    r"Fürsprecher(?:in)?|Bundesrichter(?:in)?|Gerichtsschreiber(?:in)?|Oberrichter(?:in)?|"
    r"Richter(?:in)?|Präsident(?:in)?|M\.|MM\.|Mme|Mmes|Mlle|Me|Maître|Juge|Greffier|Greffière|docteure?s?|médecin|"
    r"avv\.|avvocato|avvocata|sig\.(?:ra)?|signor[ae]?|dott\.(?:ssa)?|dottor(?:e|essa)?|[Gg]iudic[ei]|cancellier[ae]|"
    r"Juges|fédéra(?:l|le|ux|les)|federal[ei]|le|la|les|il|lo|der|die)\s*:?\s+)+"
)


PERSON_TYPES = {"private_person", "lawyer", "court_official", "expert"}
NAMED_TYPES = PERSON_TYPES | {"private_company", "public_body", "authority"}
# Role nouns are how decisions refer to parties without naming them; they are never names.
ROLE_NOUN = re.compile(
    r"(?i)^(?:(?:die|der|den|des|le|la|les|l'|il|lo|i|gli)\s+)?(?:beschwerde(?:führer|gegner)\w*|kläger\w*|beklagte\w*|"
    r"gesuch(?:steller|sgegner)\w*|berufungs\w+|beschuldigte\w*|angeklagte\w*|versicherte\w*|ehe(?:frau|mann|gatte|gattin)\w*|"
    r"mutter|vater|kind(?:er)?|sohn|tochter|mieter\w*|vermieter\w*|arbeit(?:geber|nehmer)\w*|erben?|"
    r"recourant\w*|intimé\w*|requérant\w*|demandeu\w+|défendeu\w+|enfants?|épou\w+|mère|père|fils|fille|prévenu\w*|héritiers?|"
    r"ricorrent\w+|opponent\w+|figli\w*|moglie|marito|padre|madre|imputat\w+|insorgent\w+|interessat\w+|assicurat\w+|eredi)"
    r"(?:$|\s+(?:des|der|dem|du|de|del|della|dei|degli|of)\b)"
)
NAME_WORD = re.compile(r"(?<!\w)[A-ZÀ-ÖØ-Þ][^\W\d_]+")
OFFICIAL_ROLE = re.compile(r"(?i)\b(?:judge|clerk|registrar|\w*richter\w*|gerichtsschreiber\w*|juges?|greffi\w+|giudic[ei]|cancellier\w+)\b")
INSTITUTION = re.compile(
    r"(?i)\b(?:cour|chambre|\w*gericht(?:s|e|es|en|shof)?|tribuna\w+|kammer|abteilung|corte|camera|office|amt|\w+amt|departement|"
    r"direktion|\w+direktion|commission|kommission|ministère|ministero|staatsanwaltschaft|pretura|pretore)\b"
)
PUBLIC_TITLE = re.compile(
    r"(?i)(?:rechtsanw\w*|fürsprech\w*|advokat\w*|avocat\w*|(?<!\w)me|(?<!\w)avv|avvocat\w*|\w*richter\w*|"
    r"gerichtsschreiber\w*|greffi\w+|juges?|giudic[ei]|cancellier\w+)\W{0,3}(?:(?:dr|dott|prof|lic|iur|med)\.?\s*)*$"
)
LAWYER_ROLE = re.compile(r"(?i)\b(?:lawyer|attorney|counsel|rechtsanw\w+|fürsprech\w*|avocat\w*|avvocat\w*)\b")
CITATION = re.compile(r"(?i)\b(?:art|ATF|BGE|DTF|cpv|al|abs|lit|let|fr|chf|sr|rs|consid|E)\b\.?|_\d+/\d{4}|\d+\s*/\s*\d{4}")


def plausible(surface, type_):
    """Reject what the model often mislabels: role nouns as people, citations and amounts as identifiers."""
    if type_ in NAMED_TYPES:
        return bool(NAME_WORD.search(surface)) and not ROLE_NOUN.match(surface) and not re.search(r"_\d|\d/\d", surface)
    if type_ == "identifier":
        return sum(c.isdigit() for c in surface) >= 6 and not CITATION.search(surface)
    return True
def typed(type_, role, mention):
    """The model sometimes writes the right role and the wrong type, e.g. role "judge", type private_person,
    or types a court chamber as a court official."""
    role = role.replace("_", " ")
    if type_ in PERSON_TYPES and INSTITUTION.search(mention):
        return "authority"
    if type_ in PERSON_TYPES and OFFICIAL_ROLE.search(role):
        return "court_official"
    if type_ == "private_person" and LAWYER_ROLE.search(role):
        return "lawyer"
    return type_


SPLIT = re.compile(r"\s*(?:,|;|/|\bet\b|\bund\b|\be\b|\band\b)\s*")


@dataclass(frozen=True)
class Mention:
    text: str
    type: str
    role: str
    source: str  # "apertus" or "pattern"


def surface_regex(text, suffix=""):
    """Regex for a mention with flexible whitespace and word boundaries."""
    words = [re.escape(w) for w in text.split()]
    return re.compile(r"(?<!\w)" + r"\s+".join(words) + suffix + r"(?!\w)")


def clean(text):
    return TITLES.sub("", " ".join(text.split())).strip(" ,;:")


# --- deterministic detectors -------------------------------------------------------------

PLATE_CUE = re.compile(
    r"(?i)kontrollschild|kennzeichen|nummernschild|plaque|immatricul|targa|fahrzeug|véhicule|veicolo"
)
STREET = (
    r"(?:[A-ZÄÖÜ][\wäöüß.-]*(?:strasse|straße|str\.|gasse|weg|platz|allee|rain|ring|halde|matte|quai|steig)"
    r"|(?:Rue|rue|Avenue|avenue|Av\.|Chemin|chemin|Ch\.|Route|route|Rte|Place|place|Boulevard|Quai|quai|Impasse|"
    r"Via|via|Viale|viale|Piazza|piazza|Vicolo|vicolo|Strada|strada)[ \t]+(?:[\w'’.-]+[ \t]+){0,3}?[\w'’.-]+)"
    r"[ \t]+\d{1,4}[a-z]?"
)
TOWN = r"(?:CH-)?[1-9]\d{3}[ \t]+[A-ZÄÖÜÉÈ][\w'’-]*\.?(?:[ \t]+(?:[A-ZÄÖÜÉÈ][\w'’-]*|bei|sur|près|de|di|am|an|im))?"
PATTERNS = [
    ("identifier", re.compile(r"\b756[.\s]?\d{4}[.\s]?\d{4}[.\s]?\d{2}\b")),
    ("identifier", re.compile(r"\b(?:CH|LI)\d{2}(?:\s?[0-9A-Z]{4}){4}\s?[0-9A-Z]\b")),
    ("identifier", re.compile(r"[\w.+-]+@[\w-]+(?:\.[\w-]+)+")),
    (
        "identifier",
        re.compile(
            r"(?<![\w+])(?:\+41\s?|0041\s?|0)(?:\(0\)\s?)?[1-9]\d\s?\d{3}\s?\d{2}\s?\d{2}\b"
        ),
    ),
    (
        "address",
        re.compile(STREET + r"(?:,\s*Postfach(?:\s+\d+)?)?(?:,\s*" + TOWN + ")?"),
    ),
    ("address", re.compile(r"(?<=, )" + TOWN + r"(?=\s*(?:,|\n|$))")),
    ("address", re.compile(r"\b(?:Postfach|case postale|casella postale)\s+\d+")),
]
PARCEL = re.compile(
    r"(?:Parzelle|Parz\.|Grundstück|GB-Nr\.|Kat\.-Nr\.|Katasternummer|parcelle|bien-fonds|particella|fondo|mappale)"
    r"\s*(?:Nr\.|Nr|n°|no|n\.)?\s*(\d[\d'’.]*\d|\d)"
)
PLATE = re.compile(
    r"\b(?:AG|AI|AR|BE|BL|BS|FR|GE|GL|GR|JU|LU|NE|NW|OW|SG|SH|SO|SZ|TG|TI|UR|VD|VS|ZG|ZH)\s?\d{1,3}(?:[ '’]?\d{3})?\b"
)


def pattern_mentions(text):
    """Structured identifiers, found without the model."""
    found = [(t, m.group(0)) for t, rx in PATTERNS for m in rx.finditer(text)]
    found += [("parcel_number", m.group(1)) for m in PARCEL.finditer(text)]
    found += [
        ("identifier", m.group(0))
        for m in PLATE.finditer(text)
        if PLATE_CUE.search(text, max(0, m.start() - 60), m.start())
    ]
    return [Mention(" ".join(s.split()), t, "", "pattern") for t, s in found]


# --- Apertus ---------------------------------------------------------------------------------


def chunks(text, size):
    """Split at paragraph breaks into windows of about `size` characters."""
    out, start = [], 0
    while start < len(text):
        end = min(len(text), start + size)
        if end < len(text):
            cut = text.rfind("\n", start + size // 2, end)
            end = cut + 1 if cut > 0 else end
        out.append((start, end))
        start = end
    return out


def apertus_mentions(text, language, size=6000):
    """Label every chunk; earlier findings are passed on so later chunks reuse the same roles."""
    known, mentions = {}, []
    stats = {"calls": 0, "prompt_tokens": 0, "completion_tokens": 0, "seconds": 0.0, "rejected": []}
    for start, end in chunks(text, size):
        for item in _label(text[start:end], language, known, stats):
            item["type"] = typed(item["type"], item["role"], item["mention"])
            found = verified(item["mention"], item["type"], text)
            if not found:
                stats["rejected"].append(item["mention"])
            for surface in found:
                mention = Mention(surface, item["type"], item["role"].strip(), "apertus")
                mentions.append(mention)
                known.setdefault(surface, mention)
    return mentions, stats


def _label(part, language, known, stats):
    prompt = PROMPT.format(language=LANGUAGES.get(language, language), known=_known_block(known), text=part)
    try:
        data, usage = chat_json(SYSTEM, prompt, SCHEMA)
    except LLMError as e:
        cut = part.rfind("\n", 0, len(part) // 2 + 500)
        if "max_tokens" not in str(e):
            raise
        if cut < 500:
            stats["calls"] += 1
            return [i for i in salvage_items(e.partial) if i.get("type") in TYPES]
        # The model kept listing (usually a repetition loop): label the two halves separately.
        return _label(part[:cut], language, known, stats) + _label(part[cut:], language, known, stats)
    stats["calls"] += 1
    for k in ("prompt_tokens", "completion_tokens", "seconds"):
        stats[k] += usage.get(k) or 0
    return data["mentions"]


def verified(raw, type_, text):
    """Surfaces of a model mention that really occur in the text.

    People listed together ("A und B") become separate mentions; organisation names such as
    "Dupont et Fils" stay whole.
    """
    whole = clean(raw)
    parts = [p for p in (clean(x) for x in SPLIT.split(raw)) if len(p) > 1 and plausible(p, type_)]
    found = [p for p in parts if surface_regex(p).search(text)]
    if type_ in PERSON_TYPES and len(parts) > 1 and len(found) == len(parts):
        return found
    if len(whole) > 1 and plausible(whole, type_) and surface_regex(whole).search(text):
        return [whole]
    return [p for p in found if p != whole]


def _known_block(known):
    if not known:
        return ""
    people = [
        m
        for m in known.values()
        if m.type not in ("place", "identifier", "parcel_number", "birth_date")
    ][:40]
    lines = [
        f"- {m.text}: {m.type}" + (f" ({m.role})" if m.role else "") for m in people
    ]
    return (
        "Already identified earlier in this decision (use the same type for the same names):\n"
        + "\n".join(lines)
        + "\n"
    )


SWEEP_SCHEMA = {
    "type": "object",
    "properties": {
        "names": {
            "type": "array",
            "maxItems": 40,
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "reason": {"type": "string"},
                    "type": {"type": "string", "enum": ["private_person", "private_company", "residence"]},
                },
                "required": ["name", "reason", "type"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["names"],
    "additionalProperties": False,
}

SWEEP = """Decision language: {language}.
The decision below was anonymised by a first pass: private parties appear as placeholders such as A.________ or as […].
Find what the first pass missed. List every name still written in clear that belongs to:
- private_person: a private person, e.g. a party, relative, witness, a doctor or therapist who treated a party, an expert hired by a party, a representative who is not a lawyer
- private_company: a company, shop, restaurant, hotel, farm, private clinic, association, foundation, estate, or an organisation named after a person
- residence: a place that says where a private party lives or has its seat

Do not list judges, court clerks, lawyers, courts, authorities, public institutions, cantons, countries, legal provisions, case numbers, published decisions or placeholders. Copy each name exactly as written, one name per entry. If nothing was missed, return an empty list.

Decision:
<<<
{text}
>>>"""


def titled(text, surface):
    """True if the text introduces the name with a judge's, clerk's or lawyer's title somewhere."""
    return any(
        PUBLIC_TITLE.search(text, max(0, m.start() - 40), m.start())
        for m in surface_regex(surface).finditer(text)
    )


def apertus_sweep(text, output, language, mentions, entities, size=6000):
    """Apertus rereads the anonymised output and names what the first pass missed.

    Surfaces the first pass already typed, tokens of names the pack keeps, and names the text
    introduces with a judge's, clerk's or lawyer's title are never touched, so the sweep can only
    add redactions for names nobody classified."""
    known = {m.text.casefold() for m in mentions}
    kept = {t.casefold() for e in entities if e.action == "keep" for n in e.names for t in n.split()}
    found, stats = [], {"calls": 0, "prompt_tokens": 0, "completion_tokens": 0, "seconds": 0.0}
    for start, end in chunks(output, size):
        prompt = SWEEP.format(language=LANGUAGES.get(language, language), text=output[start:end])
        items, usage = chat_list(SYSTEM, prompt, SWEEP_SCHEMA, max_tokens=2000)
        stats["calls"] += 1
        for k in ("prompt_tokens", "completion_tokens", "seconds"):
            stats[k] += usage.get(k) or 0
        for item in items:
            for surface in verified(item["name"], item["type"], text):
                folded = surface.casefold()
                if folded not in known and not set(folded.split()) <= kept and not titled(text, surface):
                    known.add(folded)
                    found.append(Mention(surface, item["type"], item["reason"].strip(), "sweep"))
    return found, stats
